# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1d1d330d0568626339659ae68d189eb1065b9d60bdde1068d647c422a6d2ca7bd2a373c670afa22fb01d076ce7fd6c18e63fcbbe84077ebfdc437bb89760e938

test:
  secret_key_base: 72ffe5eba813de71e914acd7af0efb7d885ef60c9f709b4a4e90ad84e2fc14ec2b47f77b6eaacec3bdb9c1745c67fa1a81365ed963f84e5e654f75411c9da81c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
